// SPDX-FileCopyrightText: 2026 Patrick Gaskin
// SPDX-License-Identifier: GPL-3.0-or-later

plugins {
    id 'com.android.application' version '9.3.1' apply false
    id 'com.android.library' version '9.3.1' apply false
}

allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << '-Xlint:deprecation' << '-Xlint:unchecked'
    }
}
