// SPDX-FileCopyrightText: 2026 Patrick Gaskin
// SPDX-License-Identifier: GPL-3.0-or-later

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "vento"

include ':app'
include ':backends'
include ':backends:rfb'
include ':backends:libvnc'
include ':backends:tigervnc'
include ':backends:ironrdp'
include ':backends:freerdp'
include ':backends:realvnc'
include ':control'

include ':realvnc-jni'
project(':realvnc-jni').projectDir = file('realvnc')
