// SPDX-FileCopyrightText: 2026 Patrick Gaskin
// SPDX-License-Identifier: GPL-3.0-or-later

// TigerVNC's own client behind the same JNI surface the other two RFB backends
// have, so that everything above this file is the same code whichever of the
// three is running and a comparison is between the clients.
//
// Four things here are the shim's rather than the library's, and each is forced
// by what TigerVNC's client code does and does not do:
//
//   1. One thread owns the CConnection, and every call from Java is a queued
//      command it drains. Nothing in it is safe to call from a second thread:
//      the reader and the writer share a socket, and a decode may be in flight
//      on the decoder's own threads.
//   2. There are two framebuffers. The decoders write into TigerVNC's, which
//      has no lock, and the seam promises pixels may be read from the drawing
//      thread at any moment; so the damaged region is copied into a second
//      buffer under a writer lock once the update is complete, and reads are
//      served from that.
//   3. The alpha byte is filled in during that copy. RFB's 32-bit formats leave
//      the fourth byte undefined and a decoder writes whatever the wire said;
//      Android's ARGB_8888 reads it.
//   4. The socket is opened here rather than by network::TcpSocket, whose
//      connect() is blocking and has no deadline — a mistyped address would be
//      a spinner for as long as the kernel keeps retrying. TcpSocket adopts the
//      descriptor afterwards, so everything above that is theirs.
//
// Their DecodeManager decodes on one thread per core up to four, which is not a
// parameter and is unique here: the other clients in this repository decode on
// the thread that read the socket. So this one is allowed to use more of the
// phone than they are, and a processor comparison between them has to be taken
// over the whole process rather than over a protocol thread.
//
// Two of their features are deliberately not asked for, because each would
// argue with something above this file: the **LED state** of the far end's lock
// keys, which the phone owns, and the **cursor position** pseudo-encoding,
// which is a server moving the pointer, where the whole gesture stack is built
// on this end owning it. A third, the **QEMU extended key event**, is in the
// list whatever we do — their updateEncodings always offers it — but every key
// goes out as a plain KeyEvent anyway, because this shim passes no scancode and
// their writer falls back when the code is zero. The phone owns the layout, so
// there is no scancode to pass.

#include <config.h> // theirs, generated by this module's CMake

#include <android/bitmap.h>
#include <android/log.h>
#include <jni.h>

#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <poll.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <unistd.h>

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <deque>
#include <memory>
#include <mutex>
#include <optional>
#include <shared_mutex>
#include <string>
#include <thread>
#include <vector>

#include <core/LogWriter.h>
#include <core/Logger.h>
#include <core/Region.h>
#include <core/Timer.h>

#include <network/TcpSocket.h>

#include <rdr/FdInStream.h>
#include <rdr/FdOutStream.h>
#include <rdr/InStream.h>
#include <rdr/OutStream.h>

#include <rfb/CConnection.h>
#include <rfb/CMsgWriter.h>
#include <rfb/CSecurity.h>
#include <rfb/Exception.h>
#include <rfb/PixelBuffer.h>
#include <rfb/ScreenSet.h>
#include <rfb/Security.h>
#include <rfb/encodings.h>
#include <rfb/screenTypes.h>

#define TAG "TigerVnc"
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, TAG, __VA_ARGS__)

namespace {

/// As many commands as the other shim's ring holds, and bounded for the same
/// reason: nothing is drained until the connection is up.
constexpr size_t CMD_QUEUE_MAX = 512;

// What Android's ARGB_8888 is: four bytes per pixel, red first in memory. A
// little-endian pixel with red at shift 0 puts them in that order, which is
// what makes every read from the framebuffer a memcpy.
const rfb::PixelFormat androidPF(32, 24, false, true, 255, 255, 255, 0, 8, 16);

// The two reduced formats, which are their own viewer's low and very low
// colour and the same 64 and 8 colours the other backends' rows call rgb222 and
// rgb111. Only the wire changes: the decoders convert into the framebuffer,
// which stays androidPF, so nothing downstream of a decode knows about this.
const rfb::PixelFormat lowColourPF(8, 6, false, true, 3, 3, 3, 4, 2, 0);
const rfb::PixelFormat veryLowColourPF(8, 3, false, true, 1, 1, 1, 2, 1, 0);

/** Automatic, for a level or a quality: follow the measured line speed. */
constexpr int LEVEL_AUTO = -2;

/** Their thresholds, from the viewer: full colour above 256 kbit/s. */
const rfb::PixelFormat &colourPF(int level, unsigned bps) {
    switch (level) {
        case 1:
            return lowColourPF;
        case 2:
            return veryLowColourPF;
        case LEVEL_AUTO:
            return bps > 256000 ? androidPF : lowColourPF;
        default:
            return androidPF;
    }
}

/**
 * Above 16 Mbit/s — a LAN — the second highest JPEG quality, which should be
 * perceptually lossless; below it, a lossier one. Theirs, thresholds included.
 */
int qualityFor(int level, unsigned bps) {
    return level == LEVEL_AUTO ? (bps > 16000000 ? 8 : 6) : level;
}

jclass gCallbacksClass;
jmethodID mConnected, mDesktopSize, mDamage, mFrameEnd, mCursor, mBell,
        mClipboard, mCredentialsNeeded, mQuestion, mUnverified, mClosed;

// ---- logging -------------------------------------------------------------

// TigerVNC says why it gave up in far better words than this shim could work
// out from the outside — "Unsupported security types" and which ones — and its
// exceptions carry most of that. This catches the rest, which is what a
// certificate or a protocol complaint arrives as.
class AndroidLogger : public core::Logger {
public:
    AndroidLogger() : core::Logger("android") {}

    void write(int level, const char *logname, const char *text) override {
        __android_log_print(level <= 0 ? ANDROID_LOG_WARN : ANDROID_LOG_INFO,
                            TAG, "%s: %s", logname, text);
    }
};

AndroidLogger gLogger;

void initLogging() {
    static bool done = false;
    if (!done) {
        done = true;
        gLogger.registerLogger();
        core::LogWriter::setLogParams("*:android:30");
    }
}

// ---- what a session may authenticate with --------------------------------

/**
 * Once for the process, and before the first connection is built: their
 * Security reads the list in its constructor, so a list installed afterwards is
 * a list nothing ever consults — which is what had been happening, silently,
 * with their default in force. Once rather than per session because the value
 * never differs, and a second session writing the parameter while a first reads
 * it is a race over a string for no gain.
 *
 * Their default list includes Plain, which sends the password in the clear when
 * it is not inside a TLS stack — and as a *top-level* type that is exactly what
 * it would be. The TLS* family is here: VeNCrypt over an anonymous key
 * exchange, which is encrypted against a passive listener and worth nothing
 * against an active one, since nothing about the far end is proved. It is
 * offered because a stock server with TLS switched on and no certificate
 * arranged is an ordinary setup and refusing deletes the whole session, and
 * every one of them arrives at a question ({@code Conn::confirmAnonymousTLS}).
 * X509* is the same encryption with a certificate to check, and the patched
 * sub-type choice takes one of those wherever a server offers both.
 *
 * RA2ne is here beside RA2 because "ne" is not the anonymous case: the server's
 * RSA key is checked either way, and the difference is whether the session after
 * the handshake is encrypted. Preference order is the client's, so an encrypted
 * variant wins wherever a server offers both. DH and MSLogonII are left out:
 * 64-bit Diffie-Hellman is not a check of anything in 2026.
 *
 * Conditional because an unknown name is rejected as a whole list, leaving their
 * default — which is the list this one exists to replace.
 */
void installSecurityTypes() {
    static std::once_flag once;
    std::call_once(once, [] {
        rfb::SecurityClient::secTypes.setParam("None,VncAuth"
#ifdef HAVE_GNUTLS
                                               ",X509Vnc,X509Plain,X509None"
                                               ",TLSVnc,TLSPlain,TLSNone"
#endif
#ifdef HAVE_NETTLE
                                               ",RA2,RA2_256,RA2ne,RA2ne_256"
#endif
        );
    });
}

// ---- JNI plumbing --------------------------------------------------------

/** The protocol thread is attached for its whole life; this is for the rest. */
// Anything a callback throws is pending on this thread when it returns, and
// every JNI call made while an exception is pending is undefined. The protocol
// thread stays attached for its whole life here, so a pending one would ride
// along through the rest of the update and every later callback; it is reported
// and cleared at each call instead.
static void cleared(JNIEnv *env) {
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
}

class Env {
public:
    explicit Env(JavaVM *vm) : vm_(vm) {
        if (vm_->GetEnv((void **) &env_, JNI_VERSION_1_6) != JNI_OK) {
            if (vm_->AttachCurrentThread(&env_, nullptr) != JNI_OK) {
                env_ = nullptr;
            } else {
                attached_ = true;
            }
        }
    }

    ~Env() {
        if (attached_) {
            vm_->DetachCurrentThread();
        }
    }

    JNIEnv *operator->() const { return env_; }

    JNIEnv *get() const { return env_; }

    explicit operator bool() const { return env_ != nullptr; }

private:
    JavaVM *vm_;
    JNIEnv *env_ = nullptr;
    bool attached_ = false;
};

std::string toString(JNIEnv *env, jstring js) {
    if (js == nullptr) {
        return {};
    }
    const char *c = env->GetStringUTFChars(js, nullptr);
    std::string out = c ? c : "";
    if (c) {
        env->ReleaseStringUTFChars(js, c);
    }
    return out;
}

// The clipboard is the one string here that is not an address or a password,
// which is to say the one that can hold anything a person has copied — and JNI's
// own UTF-8 is not UTF-8: it encodes a character outside the basic plane as a
// surrogate pair of three-byte sequences, which TigerVNC's clipboard validator
// rejects outright. So these two convert through UTF-16, which is what a Java
// string is.
std::string toUtf8(JNIEnv *env, jstring js) {
    if (js == nullptr) {
        return {};
    }
    const jsize n = env->GetStringLength(js);
    const jchar *chars = env->GetStringChars(js, nullptr);
    std::string out;
    if (chars != nullptr) {
        out.reserve((size_t) n);
        for (jsize i = 0; i < n; i++) {
            uint32_t cp = chars[i];
            if (cp >= 0xD800 && cp <= 0xDBFF && i + 1 < n
                    && chars[i + 1] >= 0xDC00 && chars[i + 1] <= 0xDFFF) {
                cp = 0x10000 + ((cp - 0xD800) << 10) + (chars[++i] - 0xDC00);
            }
            if (cp < 0x80) {
                out += (char) cp;
            } else if (cp < 0x800) {
                out += (char) (0xC0 | (cp >> 6));
                out += (char) (0x80 | (cp & 0x3F));
            } else if (cp < 0x10000) {
                out += (char) (0xE0 | (cp >> 12));
                out += (char) (0x80 | ((cp >> 6) & 0x3F));
                out += (char) (0x80 | (cp & 0x3F));
            } else {
                out += (char) (0xF0 | (cp >> 18));
                out += (char) (0x80 | ((cp >> 12) & 0x3F));
                out += (char) (0x80 | ((cp >> 6) & 0x3F));
                out += (char) (0x80 | (cp & 0x3F));
            }
        }
        env->ReleaseStringChars(js, chars);
    }
    return out;
}

jstring fromUtf8(JNIEnv *env, const char *utf8) {
    std::vector<jchar> out;
    for (const uint8_t *p = (const uint8_t *) utf8; *p != 0;) {
        uint32_t cp;
        int extra;
        if (*p < 0x80) { cp = *p; extra = 0; }
        else if ((*p & 0xE0) == 0xC0) { cp = *p & 0x1F; extra = 1; }
        else if ((*p & 0xF0) == 0xE0) { cp = *p & 0x0F; extra = 2; }
        else if ((*p & 0xF8) == 0xF0) { cp = *p & 0x07; extra = 3; }
        else { p++; continue; }
        p++;
        for (int k = 0; k < extra && (*p & 0xC0) == 0x80; k++, p++) {
            cp = (cp << 6) | (*p & 0x3F);
        }
        if (cp >= 0x10000) {
            cp -= 0x10000;
            out.push_back((jchar) (0xD800 + (cp >> 10)));
            out.push_back((jchar) (0xDC00 + (cp & 0x3FF)));
        } else {
            out.push_back((jchar) cp);
        }
    }
    // An empty vector's data() is null, and a null with a length of zero is not
    // a pointer JNI is required to accept.
    static const jchar none = 0;
    return env->NewString(out.empty() ? &none : out.data(), (jsize) out.size());
}

// ---- the framebuffer the decoders write into -----------------------------

class Framebuffer : public rfb::ManagedPixelBuffer {
public:
    Framebuffer(int w, int h) : rfb::ManagedPixelBuffer(androidPF, w, h) {}

    // Called by whichever thread decoded the rectangle, which with more than
    // one decoder thread is not the protocol thread.
    void commitBufferRW(const core::Rect &r) override {
        rfb::ManagedPixelBuffer::commitBufferRW(r);
        const std::lock_guard<std::mutex> guard(lock);
        damage.assign_union(core::Region(r));
    }

    core::Region takeDamage() {
        const std::lock_guard<std::mutex> guard(lock);
        core::Region taken = damage;
        damage.clear();
        return taken;
    }

private:
    std::mutex lock;
    core::Region damage;
};

// ---- the command queue ---------------------------------------------------

enum CmdType {
    CMD_POINTER,
    CMD_KEY_DOWN,
    CMD_KEY_UP,
    CMD_RELEASE_KEYS,
    CMD_CLIPBOARD,
    CMD_PICTURE,
    CMD_RESIZE,
    CMD_DISCONNECT,
};

struct Cmd {
    CmdType type;
    int a = 0, b = 0, c = 0;
    std::string text{}; // every post but the clipboard's leaves this out
};

class Session;

// ---- the connection ------------------------------------------------------

class Conn : public rfb::CConnection {
public:
    explicit Conn(Session *session) : s(session) {
        supportsLocalCursor = true;
        supportsDesktopResize = true;
    }

    /** Theirs is protected, and this is set from the session's own state. */
    void offerH264(bool on) { setSupportsH264(on); }

    /** The one throughput number this client has, for whatever follows it. */
    unsigned bandwidth() const { return bpsEstimate; }

    void initDone() override;

    void setName(const char *name) override;

    void resizeFramebuffer() override;

    void setExtendedDesktopSize(unsigned reason, unsigned result, int w, int h,
                                const rfb::ScreenSet &layout) override;

    void framebufferUpdateStart() override;

    void framebufferUpdateEnd() override;

    bool dataRect(const core::Rect &r, int encoding) override;

    void setCursor(int width, int height, const core::Point &hotspot,
                   const uint8_t *data) override;

    void bell() override;

    void getUserPasswd(bool secure, std::string *user, std::string *password) override;

    bool showMsgBox(rfb::MsgBoxFlags flags, const char *title, const char *text) override;

    void confirmAnonymousTLS() override;

    void handleClipboardAnnounce(bool available) override;

    void handleClipboardData(const char *data) override;

    void handleClipboardRequest() override;

private:
    void newFramebuffer(int w, int h);

    Session *s;
    /** Theirs: they own it and `close()` deletes it, so it is asked for
        rather than kept. */
    Framebuffer *framebuffer() {
        return static_cast<Framebuffer *>(getFramebuffer());
    }
    int lastServerEncoding = -1;

    // The viewer's own estimate, kept the same way: bytes read over the time
    // an update took, weighted by how long that was, against a one-second
    // window. It is the only throughput number TigerVNC has.
    unsigned bpsEstimate = 20000000;
    size_t updateStartPos = 0;
    struct timeval updateStartTime = {};
};

// ---- the session ---------------------------------------------------------

class Session {
public:
    Session(JNIEnv *env, jobject callbacks, std::string address, std::string userName,
            std::string password, bool shared, bool anonymousTls, int encoding,
            int compressLevel, int qualityLevel, int colorLevel, bool h264,
            int connectTimeoutMs)
            : address_(std::move(address)), userName_(std::move(userName)),
              password_(std::move(password)), shared_(shared),
              anonymousTls_(anonymousTls), encoding_(encoding),
              compressLevel_(compressLevel), qualityLevel_(qualityLevel),
              colorLevel_(colorLevel), h264_(h264),
              connectTimeoutMs_(connectTimeoutMs) {
        env->GetJavaVM(&vm_);
        callbacks_ = env->NewGlobalRef(callbacks);
        if (pipe(wake_) == 0) {
            for (int fd : wake_) {
                fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
            }
        }
    }

    bool start() {
        if (wake_[0] < 0) {
            return false;
        }
        thread_ = std::thread([this] { run(); });
        return true;
    }

    void destroy() {
        disconnect();
        if (thread_.joinable()) {
            thread_.join();
        }
        const Env env(vm_);
        if (env) {
            env->DeleteGlobalRef(callbacks_);
        }
        close(wake_[0]);
        close(wake_[1]);
    }

    JavaVM *vm() { return vm_; }

    jobject callbacks() { return callbacks_; }

    // ---- calls from Java --------------------------------------------------

    void post(Cmd cmd) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            if (quit_) {
                return;
            }
            // Motion coalesces onto the tail of the queue: the protocol thread
            // can be inside a decode, and by the time it drains, every position
            // but the last is somewhere the pointer no longer is. A button
            // change is a different event and is never merged away.
            if (cmd.type == CMD_POINTER && !queue_.empty()
                    && queue_.back().type == CMD_POINTER && queue_.back().c == cmd.c) {
                queue_.back() = std::move(cmd);
            } else {
                // Bounded like the other shim's ring, and for the same reason:
                // nothing is drained until the connection is up, and answering
                // a password prompt can take as long as somebody likes. The
                // oldest goes, since the newest is what the far end still needs
                // to be told.
                if (queue_.size() >= CMD_QUEUE_MAX) {
                    queue_.pop_front();
                }
                queue_.push_back(std::move(cmd));
            }
        }
        wake();
    }

    void disconnect() {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            quit_ = true;
            paused_ = false;
        }
        answered_.notify_all();
        wake();
        // The doorbell is only looked at between messages, and a read that has
        // started blocks inside their stream until the rest of the message
        // arrives — so a server that accepts the connection and then stalls
        // would hold whoever called destroy(), which is the main thread. The
        // descriptor stays TcpSocket's; only the shutdown is ours.
        const int fd = fd_.load();
        if (fd >= 0) {
            ::shutdown(fd, SHUT_RDWR);
        }
    }

    // Stop reading the socket, which in the other two RFB backends is the whole
    // pause: an RFB server sends nothing that was not asked for, so leaving the
    // last update unread is what makes it wait. Not here — this client turns
    // continuous updates on, so the server pushes without being asked. What
    // stops it instead is TigerVNC's own congestion control: it sends fences
    // and waits for the replies, which a client that is not reading does not
    // send. Same effect, different mechanism, and worth knowing before
    // measuring a backgrounded session against the other two.
    void setFocus(bool focused) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            paused_ = !focused;
        }
        wake();
    }

    void setViewOnly(bool viewOnly) { viewOnly_ = viewOnly; }

    bool viewOnly() const { return viewOnly_; }

    /** Set from the protocol thread, read from whichever asks. */
    void setCanResize(bool can) { canResize_ = can; }

    /** The far end's screen layout, flattened four ints per screen. */
    void setScreens(std::vector<jint> screens) {
        const std::lock_guard<std::mutex> guard(screensLock_);
        screens_ = std::move(screens);
    }

    std::vector<jint> screens() const {
        const std::lock_guard<std::mutex> guard(screensLock_);
        return screens_;
    }

    void setConnected() {
        const std::lock_guard<std::mutex> guard(lock_);
        connected_ = true;
    }

    /* More than one screen says no, and that is the shim's limitation rather
       than the library's: what a resize sends is a single screen covering the
       desktop, so granting one would merge somebody's monitors into one. */
    bool canResize() const {
        if (!canResize_ || viewOnly_) {
            return false;
        }
        const std::lock_guard<std::mutex> guard(screensLock_);
        return screens_.size() <= 4;
    }

    void answerCredentials(const std::string &user, const char *password) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            credUser_ = user;
            credPassword_ = password ? password : "";
            credCancelled_ = password == nullptr;
            credAnswered_ = true;
            if (credCancelled_) {
                quit_ = true;
            }
        }
        answered_.notify_all();
        wake();
    }

    /** Blocks the protocol thread until Java answers: a dialog and a person. */
    bool askCredentials(bool needsUserName, std::string *user, std::string *password) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            credAnswered_ = false;
        }
        const Env env(vm_);
        if (env) {
            env->CallVoidMethod(callbacks_, mCredentialsNeeded, (jboolean) needsUserName);
            cleared(env.get());
        }
        std::unique_lock<std::mutex> guard(lock_);
        answered_.wait(guard, [this] { return credAnswered_ || quit_; });
        if (credCancelled_ || quit_) {
            return false;
        }
        if (user != nullptr) {
            *user = credUser_;
        }
        *password = credPassword_;
        return true;
    }

    void answerQuestion(bool yes) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            questionYes_ = yes;
            questionAnswered_ = true;
            if (!yes) {
                quit_ = true;
            }
        }
        answered_.notify_all();
        wake();
    }

    /** Blocks the protocol thread, as the credentials prompt does. */
    bool askQuestion(const char *title, const char *text) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            questionAnswered_ = false;
        }
        const Env env(vm_);
        if (env) {
            jstring jTitle = fromUtf8(env.get(), title);
            jstring jText = fromUtf8(env.get(), text);
            env->CallVoidMethod(callbacks_, mQuestion, jTitle, jText);
            cleared(env.get());
            env->DeleteLocalRef(jTitle);
            env->DeleteLocalRef(jText);
        }
        std::unique_lock<std::mutex> guard(lock_);
        answered_.wait(guard, [this] { return questionAnswered_ || quit_; });
        return questionYes_ && !quit_;
    }

    /** The same wait again, for a far end with no identity to show at all. */
    bool askUnverified(const char *why) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            questionAnswered_ = false;
        }
        const Env env(vm_);
        if (env) {
            jstring jWhy = fromUtf8(env.get(), why);
            env->CallVoidMethod(callbacks_, mUnverified, jWhy);
            cleared(env.get());
            env->DeleteLocalRef(jWhy);
        }
        std::unique_lock<std::mutex> guard(lock_);
        answered_.wait(guard, [this] { return questionAnswered_ || quit_; });
        return questionYes_ && !quit_;
    }

    bool anonymousTls() const { return anonymousTls_; }

    void setPicture(int encoding, int compressLevel, int qualityLevel, int colorLevel,
                    bool h264) {
        const std::lock_guard<std::mutex> guard(lock_);
        encoding_ = encoding;
        compressLevel_ = compressLevel;
        qualityLevel_ = qualityLevel;
        colorLevel_ = colorLevel;
        h264_ = h264;
    }

    /** Only ever the protocol thread's, and only between messages. */
    void applyPicture(Conn *conn) {
        // The settings are copied out and the lock released before anything is
        // said to the connection: refreshFramebuffer can write and flush, which
        // blocks on a server that has stopped reading, and this is the mutex
        // every touch event and destroy() takes.
        int encoding, compressLevel, qualityLevel, colorLevel;
        bool h264;
        {
            const std::lock_guard<std::mutex> guard(lock_);
            encoding = encoding_;
            compressLevel = compressLevel_;
            qualityLevel = qualityLevel_;
            colorLevel = colorLevel_;
            h264 = h264_;
        }
        // Before the preference, which is one of the things that re-sends
        // SetEncodings: this decides whether H.264 is in the list at all, and
        // asking for it as a preference while it is not offered would leave the
        // server the encoding it already had. It marks the list changed itself,
        // because otherwise moving this row alone re-sends nothing.
        conn->offerH264(h264);
        conn->setPreferredEncoding(encoding);
        conn->setCompressLevel(compressLevel);
        const int quality = qualityFor(qualityLevel, conn->bandwidth());
        // Tight's JPEG is enabled by there being a quality level at all, so
        // lossless is the absence of one rather than a value of it. On the
        // connection rather than on the library's global parameter, which is a
        // patch of ours: two sessions at different qualities would otherwise
        // each be deciding the other's encoding list.
        conn->setNoJpeg(quality < 0);
        conn->setQualityLevel(quality);
        // Safe at any moment, which is the library's doing rather than ours:
        // their setPF only records the format, and the connection switches to it
        // where nothing is in flight — for continuous updates by stopping them
        // and waiting for the end-of-continuous-updates message. libvncclient
        // has no such point, which is why the same row is not live there.
        const rfb::PixelFormat &pf = colourPF(colorLevel, conn->bandwidth());
        if (!requestedPF_ || !(*requestedPF_ == pf)) {
            requestedPF_ = pf;
            conn->setPF(pf);
            setViewerPF(pf);
            // A format decides how the *next* rectangle arrives, and a desktop
            // that is not changing sends none — so the whole picture is asked
            // for again, or moving this row does nothing anybody can see. Their
            // own refresh, which knows to wait where an update is in flight.
            conn->refreshFramebuffer();
        }
    }

    /** Whether anything about the picture follows the measured line speed. */
    bool picturesItself() {
        const std::lock_guard<std::mutex> guard(lock_);
        return qualityLevel_ == LEVEL_AUTO || colorLevel_ == LEVEL_AUTO;
    }

    /** The copy the drawing thread reads, and the only pixels it may see. */
    bool readRegion(JNIEnv *env, int x, int y, int w, int h,
                    jobject bitmap, int dstX, int dstY);

    bool readThumbnail(JNIEnv *env, int step, jobject bitmap);

    jobjectArray info(JNIEnv *env);

    // ---- called from the connection (protocol thread) ---------------------

    void resized(int w, int h, bool first) {
        {
            const std::unique_lock<std::shared_mutex> guard(fbLock_);
            shadow_.assign((size_t) w * (size_t) h, 0xFF000000u);
            shadowW_ = w;
            shadowH_ = h;
        }
        const Env env(vm_);
        if (env) {
            env->CallVoidMethod(callbacks_, first ? mConnected : mDesktopSize, w, h);
            cleared(env.get());
        }
    }

    /** The whole of the second framebuffer's cost, and the only place it is
        paid: once per damaged rectangle per update, under the writer lock. */
    void publish(Framebuffer *fb, const std::vector<core::Rect> &rects) {
        {
            const std::unique_lock<std::shared_mutex> guard(fbLock_);
            for (const core::Rect &r : rects) {
                int stride = 0;
                const uint8_t *src = fb->getBuffer(r, &stride);
                for (int row = 0; row < r.height(); row++) {
                    const uint32_t *in = (const uint32_t *) src + (size_t) row * stride;
                    uint32_t *out = shadow_.data()
                            + (size_t) (r.tl.y + row) * (size_t) shadowW_ + r.tl.x;
                    for (int col = 0; col < r.width(); col++) {
                        out[col] = in[col] | 0xFF000000u;
                    }
                }
            }
        }
        const Env env(vm_);
        if (env) {
            for (const core::Rect &r : rects) {
                env->CallVoidMethod(callbacks_, mDamage, r.tl.x, r.tl.y, r.width(), r.height());
                cleared(env.get());
            }
            env->CallVoidMethod(callbacks_, mFrameEnd);
            cleared(env.get());
        }
    }

    void closed(const std::string &detail) {
        {
            const std::lock_guard<std::mutex> guard(lock_);
            if (closedReported_) {
                return;
            }
            closedReported_ = true;
        }
        const Env env(vm_);
        if (env) {
            // Through the converter, not NewStringUTF: an auth_error's text
            // quotes the reason string the *server* sent, so these are not
            // bytes this file chose.
            jstring d = fromUtf8(env.get(), detail.c_str());
            env->CallVoidMethod(callbacks_, mClosed, d);
            cleared(env.get());
            env->DeleteLocalRef(d);
        }
    }

    std::string storedUser() const { return userName_; }

    std::string takeStoredPassword() {
        std::string p = password_;
        password_.clear();
        return p;
    }

    const std::string &pendingClipboard() const { return clipboardOut_; }

private:
    void run();

    void wake() {
        const char one = 1;
        (void) !write(wake_[1], &one, 1);
    }

    /** Non-blocking connect with a deadline, and the descriptor is the result. */
    int openSocket(std::string *why);

    const std::string address_;
    const std::string userName_;
    std::string password_;
    const bool shared_;
    const bool anonymousTls_;
    int encoding_;
    int compressLevel_;
    int qualityLevel_;
    int colorLevel_;
    // The format last asked for, which is not the connection's until it has
    // somewhere safe to switch — so the comparison that decides whether
    // anything changed has to be against this rather than against server.pf().
    std::optional<rfb::PixelFormat> requestedPF_;
    bool h264_;
    const int connectTimeoutMs_;

    JavaVM *vm_ = nullptr;
    jobject callbacks_ = nullptr;
    std::thread thread_;
    int wake_[2] = {-1, -1};
    std::atomic<int> fd_{-1}; // the socket's, for disconnect(); owned by TcpSocket

    std::mutex lock_;
    std::condition_variable answered_;
    std::deque<Cmd> queue_;
    bool quit_ = false;
    bool paused_ = false;
    bool closedReported_ = false;
    bool connected_ = false;
    bool credAnswered_ = false;
    bool credCancelled_ = false;
    bool questionAnswered_ = false;
    bool questionYes_ = false;
    std::string credUser_;
    std::string credPassword_;
    std::string clipboardOut_;
    std::atomic<bool> viewOnly_{false};
    std::atomic<bool> canResize_{false};
    mutable std::mutex screensLock_;
    std::vector<jint> screens_;

    std::shared_mutex fbLock_;
    std::vector<uint32_t> shadow_;
    int shadowW_ = 0;
    int shadowH_ = 0;

    std::string serverHost_;
    int serverPort_ = 0;

    // The facts the panel asks for, kept where anyone can read them rather than
    // fetched: every one of them lives in the connection, which only the
    // protocol thread may touch, and it can be inside a decode or behind an
    // unanswered password prompt when the question arrives.
    std::mutex infoLock_;
    std::string infoDesktop_, infoProtocol_, infoSecurity_, infoServerPF_, infoViewerPF_;
    std::atomic<int> infoEncoding_{-1};
    std::atomic<unsigned> infoLineSpeed_{0};
    std::atomic<jlong> infoReceived_{-1}, infoSent_{-1};

public:
    void setConnectionFacts(const std::string &desktop, const std::string &protocol,
                            const std::string &security, const std::string &serverPF) {
        const std::lock_guard<std::mutex> guard(infoLock_);
        infoDesktop_ = desktop;
        infoProtocol_ = protocol;
        infoSecurity_ = security;
        infoServerPF_ = serverPF;
    }

    void setDesktopName(const std::string &desktop) {
        const std::lock_guard<std::mutex> guard(infoLock_);
        infoDesktop_ = desktop;
    }

    void setLiveFacts(int encoding, unsigned lineSpeed) {
        infoEncoding_ = encoding;
        infoLineSpeed_ = lineSpeed;
    }

    /** What the connection's own two streams have carried, published from the
        protocol thread because they may only be read there. Both are the
        connection's rather than the socket's, so this is the protocol inside
        whatever is encrypting it. */
    void setTraffic(jlong received, jlong sent) {
        infoReceived_ = received;
        infoSent_ = sent;
    }

    void traffic(jlong *out) const {
        out[0] = infoReceived_.load();
        out[1] = infoSent_.load();
    }

    /** What was last asked for on the wire, which is not the framebuffer's. */
    void setViewerPF(const rfb::PixelFormat &pf) {
        char text[100];
        pf.print(text, sizeof(text));
        const std::lock_guard<std::mutex> guard(infoLock_);
        infoViewerPF_ = text;
    }

private:
    void runCmd(Conn *conn, Cmd &cmd);
};

// ---- Conn, which is where the protocol reaches the session ---------------

void Conn::newFramebuffer(int w, int h) {
    setFramebuffer(new Framebuffer(w, h));
}

void Conn::initDone() {
    // The server's own format, read before anything is asked for: after setPF
    // this is whatever we asked for, which is the other row.
    char pf[100];
    server.pf().print(pf, sizeof(pf));

    s->applyPicture(this);
    newFramebuffer(server.width(), server.height());

    char protocol[32];
    snprintf(protocol, sizeof(protocol), "RFB %d.%d", server.majorVersion, server.minorVersion);
    // Their own name for the type, and for the three with no certificate under
    // them what that leaves: a session saying only "TLSVnc" would be claiming
    // the identity check this family does not have.
    std::string security;
    if (csecurity != nullptr) {
        const int type = csecurity->getType();
        security = rfb::secTypeName(type);
        if (type == rfb::secTypeTLSNone || type == rfb::secTypeTLSVnc
            || type == rfb::secTypeTLSPlain) {
            security += ", encrypted and unverified";
        }
    }
    s->setConnectionFacts(server.name(), protocol, security.c_str(), pf);

    s->resized(server.width(), server.height(), true);
    s->setConnected();
}

void Conn::setName(const char *name) {
    rfb::CConnection::setName(name);
    s->setDesktopName(server.name());
}

// Called for every desktop-size rectangle, which a server sends at the head of
// every *non-incremental* update — so this is only a resize when the size has
// actually changed, and treating it as one otherwise asks for a full update
// that provokes the next one.
void Conn::resizeFramebuffer() {
    if (framebuffer() != nullptr && framebuffer()->width() == server.width()
            && framebuffer()->height() == server.height()) {
        return;
    }
    newFramebuffer(server.width(), server.height());
    s->resized(server.width(), server.height(), false);
    // Nothing survives the reallocation, so ask for all of it.
    refreshFramebuffer();
}

// The library's own handler sets server.supportsSetDesktopSize and, where the
// answer is yes, the new size — which reaches Java through resizeFramebuffer
// like any other. What is added here is the flag Java may read at any moment,
// and the one thing the library does not carry out of the protocol thread: the
// result code, which is the only place a refusal is stated at all.
void Conn::setExtendedDesktopSize(unsigned reason, unsigned result, int w, int h,
                                  const rfb::ScreenSet &layout) {
    rfb::CConnection::setExtendedDesktopSize(reason, result, w, h, layout);
    s->setCanResize(true);
    // The rectangle's own layout rather than server.screenLayout(), which the
    // base class leaves at the old one when the server has said no.
    std::vector<jint> screens;
    screens.reserve(layout.num_screens() * 4);
    for (const rfb::Screen &screen : layout) {
        screens.push_back(screen.dimensions.tl.x);
        screens.push_back(screen.dimensions.tl.y);
        screens.push_back(screen.dimensions.width());
        screens.push_back(screen.dimensions.height());
    }
    s->setScreens(std::move(screens));
    if (reason == rfb::reasonClient && result != rfb::resultSuccess) {
        // Not the size that was asked for: a refusal carries the size the
        // desktop still has, which is the one thing this rectangle is sure to
        // say. 1 is prohibited, 2 out of resources, 3 an invalid layout.
        LOGW("the server refused a resize and stayed at %dx%d (result %u)", w, h, result);
    }
}

void Conn::framebufferUpdateStart() {
    rfb::CConnection::framebufferUpdateStart();
    gettimeofday(&updateStartTime, nullptr);
    updateStartPos = getInStream()->pos();
}

void Conn::framebufferUpdateEnd() {
    rfb::CConnection::framebufferUpdateEnd();

    struct timeval now;
    gettimeofday(&now, nullptr);
    unsigned long long elapsed = (now.tv_sec - updateStartTime.tv_sec) * 1000000ull;
    elapsed += now.tv_usec - updateStartTime.tv_usec;
    if (elapsed == 0) {
        elapsed = 1;
    }
    const unsigned long long bps =
            (unsigned long long) (getInStream()->pos() - updateStartPos) * 8 * 1000000 / elapsed;
    unsigned long long weight = elapsed; // µs: upstream's fraction of a second, in millionths
    if (weight > 200000) {
        weight = 200000;
    }
    bpsEstimate = (unsigned) (((unsigned long long) bpsEstimate * (1000000 - weight)
            + bps * weight) / 1000000);
    s->setLiveFacts(lastServerEncoding, bpsEstimate);

    // Where anything about the picture follows the line speed, this is where
    // the viewer moves it too: the estimate has just changed, and setting a
    // quality or a format here only marks it — both go out with the request for
    // the next update rather than into the middle of this one.
    if (s->picturesItself()) {
        s->applyPicture(this);
    }

    Framebuffer *fb = framebuffer();
    if (fb == nullptr) {
        return;
    }
    core::Region damage = fb->takeDamage();
    std::vector<core::Rect> rects;
    damage.get_rects(&rects);
    if (!rects.empty()) {
        s->publish(fb, rects);
    }
}

bool Conn::dataRect(const core::Rect &r, int encoding) {
    if (encoding != rfb::encodingCopyRect) {
        lastServerEncoding = encoding;
    }
    return rfb::CConnection::dataRect(r, encoding);
}

/* FNV-1a over a cursor's pixels, which is its identity in CursorCache — so
   this, the other shims' copies of it and the Java one all have to agree.
   Computed while the pixels are still hot from the conversion above; what it
   saves on the other side is a bitmap and a texture per cursor change. */
static jlong cursorHash(const jint *argb, int width, int height) {
    uint64_t h = 0xcbf29ce484222325ull;
    h = (h ^ (uint32_t) width) * 0x100000001b3ull;
    h = (h ^ (uint32_t) height) * 0x100000001b3ull;
    for (int i = 0; i < width * height; i++) {
        h = (h ^ (uint32_t) argb[i]) * 0x100000001b3ull;
    }
    return (jlong) h;
}

void Conn::setCursor(int width, int height, const core::Point &hotspot,
                     const uint8_t *data) {
    rfb::CConnection::setCursor(width, height, hotspot, data);

    const Env env(s->vm());
    if (!env) {
        return;
    }
    jintArray argb = nullptr;
    jlong hash = 0;
    if (width > 0 && height > 0 && data != nullptr) {
        argb = env->NewIntArray(width * height);
        if (argb != nullptr) {
            jint *out = env->GetIntArrayElements(argb, nullptr);
            // Four bytes a pixel, red first — the order the cursor readers
            // write whichever encoding carried it.
            for (int i = 0; i < width * height; i++) {
                out[i] = (jint) (((uint32_t) data[i * 4 + 3] << 24)
                        | ((uint32_t) data[i * 4] << 16)
                        | ((uint32_t) data[i * 4 + 1] << 8)
                        | (uint32_t) data[i * 4 + 2]);
            }
            hash = cursorHash(out, width, height);
            env->ReleaseIntArrayElements(argb, out, 0);
        }
    }
    env->CallVoidMethod(s->callbacks(), mCursor, argb, width, height, hotspot.x, hotspot.y, hash);
    cleared(env.get());
    if (argb != nullptr) {
        env->DeleteLocalRef(argb);
    }
}

void Conn::bell() {
    const Env env(s->vm());
    if (env) {
        env->CallVoidMethod(s->callbacks(), mBell);
        cleared(env.get());
    }
}

void Conn::getUserPasswd(bool /*secure*/, std::string *user, std::string *password) {
    const std::string stored = s->takeStoredPassword();
    if (!stored.empty()) {
        if (user != nullptr) {
            *user = s->storedUser();
        }
        *password = stored;
        return;
    }
    // A cancelled prompt is a cancelled connection, and saying so as their own
    // exception is what stops the handshake from carrying on with an empty one.
    if (!s->askCredentials(user != nullptr, user, password)) {
        throw rfb::auth_cancelled();
    }
}

// Every one of these is about the far end's identity — an RSA-AES key
// fingerprint, or a certificate that verified against nothing — so the answer
// is a person's and the handshake waits for it.
bool Conn::showMsgBox(rfb::MsgBoxFlags /*flags*/, const char *title, const char *text) {
    return s->askQuestion(title, text);
}

// The tunnel came up with no certificate under it, which is a different
// question from whether an identity is the right one: there is nothing to show
// and nothing to remember, so it is asked in the app's own words every time.
//
// The refusal is here rather than in the offer because the type list is one
// string for the process: the sub-types are always offered and a connection
// that does not want them says so at this point, one handshake later than it
// would like and before anything has been authenticated inside it.
void Conn::confirmAnonymousTLS() {
    if (!s->anonymousTls()) {
        throw std::runtime_error(
                "This server only offers encryption without a peer certificate, which is not enabled for this connection.");
    }
    if (!s->askUnverified("This server offers encryption without a peer certificate.")) {
        throw rfb::auth_cancelled();
    }
}

void Conn::handleClipboardAnnounce(bool available) {
    if (available) {
        requestClipboard();
    }
}

void Conn::handleClipboardData(const char *data) {
    const Env env(s->vm());
    if (env && data != nullptr) {
        jstring js = fromUtf8(env.get(), data);
        if (js != nullptr) {
            env->CallVoidMethod(s->callbacks(), mClipboard, js);
            cleared(env.get());
            env->DeleteLocalRef(js);
        }
    }
}

void Conn::handleClipboardRequest() {
    if (!s->viewOnly()) {
        sendClipboardData(s->pendingClipboard().c_str());
    }
}

// ---- the protocol thread -------------------------------------------------

void Session::runCmd(Conn *conn, Cmd &cmd) {
    switch (cmd.type) {
        case CMD_POINTER:
            if (!viewOnly_) {
                // Bits 0–8: the seam's mask is RFB's, and TigerVNC carries the
                // eighth and ninth through the extended pointer message when
                // the server has asked for it.
                conn->writer()->writePointerEvent(core::Point(cmd.a, cmd.b),
                                                  (uint16_t) (cmd.c & 0x1FF));
            }
            break;
        case CMD_KEY_DOWN:
            if (!viewOnly_) {
                // The key's identity is the seam's `keyId`, which is exactly
                // what TigerVNC's `systemKeyCode` is for: it keeps the map of
                // held keys itself and releases the keysym recorded at press
                // time. The other two clients need that map in the shim.
                conn->sendKeyPress(cmd.b, 0, (uint32_t) cmd.a);
            }
            break;
        case CMD_KEY_UP:
            if (!viewOnly_) {
                conn->sendKeyRelease(cmd.a);
            }
            break;
        case CMD_RELEASE_KEYS:
            if (!viewOnly_) {
                conn->releaseAllKeys();
            }
            break;
        case CMD_CLIPBOARD:
            // The extended clipboard is an announcement and a request, not a
            // send: the server asks for the text if it wants it, which is when
            // `pendingClipboard` is read.
            clipboardOut_ = cmd.text;
            if (!viewOnly_) {
                conn->announceClipboard(true);
            }
            break;
        case CMD_PICTURE:
            applyPicture(conn);
            break;
        case CMD_RESIZE: {
            // Guarded rather than attempted: writeSetDesktopSize throws where
            // the server never offered one, and an exception out of here ends
            // the session.
            if (viewOnly_ || !conn->server.supportsSetDesktopSize
                    || (conn->server.width() == cmd.a && conn->server.height() == cmd.b)) {
                break;
            }
            // One screen covering the desktop, which is the FLTK viewer's
            // windowed case and the only one a phone has. The screen kept is
            // the server's own, so its id and flags go back as they came: a
            // server matches what it is sent against the screens it has.
            rfb::ScreenSet layout = conn->server.screenLayout();
            while (layout.num_screens() > 1) {
                rfb::ScreenSet::iterator second = layout.begin();
                ++second;
                layout.remove_screen(second->id);
            }
            if (layout.num_screens() == 0) {
                layout.add_screen(rfb::Screen());
            }
            layout.begin()->dimensions.tl.x = 0;
            layout.begin()->dimensions.tl.y = 0;
            layout.begin()->dimensions.br.x = cmd.a;
            layout.begin()->dimensions.br.y = cmd.b;
            if (!layout.validate(cmd.a, cmd.b)) {
                LOGW("not asking for %dx%d: the layout it would need is not valid", cmd.a, cmd.b);
                break;
            }
            conn->writer()->writeSetDesktopSize(cmd.a, cmd.b, layout);
            break;
        }
        case CMD_DISCONNECT: {
            const std::lock_guard<std::mutex> guard(lock_);
            quit_ = true;
            break;
        }
    }
}

// `host::port` is the one unbracketed address with two colons in it that is not
// an IPv6 literal somebody left the brackets off.
static bool bareLiteral(const std::string &address) {
    const size_t first = address.find(':');
    const size_t last = address.rfind(':');
    if (first == std::string::npos || first == last) {
        return false;
    }
    return !(last == first + 1 && address.find(':', last + 1) == std::string::npos);
}

// An address is `host`, `host:port`, `[literal]` or `[literal]:port`. A bare
// IPv6 literal is refused in words rather than guessed at, because `:1` is a
// display number here and `::1:1` cannot be an address and a display at once —
// what the guess used to produce was `::`, which is the wildcard address. The
// split itself is upstream's: it has the display rule, the `host::port` escape
// from it, and unit tests, none of which is worth writing again beside it.
static bool splitAddress(const std::string &address, std::string *host, int *port,
                         std::string *why) {
    const size_t from = address.find_first_not_of(" \t");
    const size_t to = address.find_last_not_of(" \t");
    const std::string trimmed =
            from == std::string::npos ? "" : address.substr(from, to - from + 1);
    if (trimmed.empty() || trimmed[0] == ':') {
        *why = "No host in address";
        return false;
    }
    if (trimmed[0] != '[' && bareLiteral(trimmed)) {
        *why = "IPv6 addresses must be bracketed, like [::1]:5900, not " + trimmed;
        return false;
    }
    try {
        network::getHostAndPort(trimmed.c_str(), host, port, 5900);
    } catch (const std::exception &e) {
        *why = std::string("Not an address: ") + e.what();
        return false;
    }
    return true;
}

int Session::openSocket(std::string *why) {
    std::string host;
    int port = 5900;
    if (!splitAddress(address_, &host, &port, why)) {
        return -1;
    }

    char service[16];
    snprintf(service, sizeof(service), "%d", port);
    struct addrinfo hints = {};
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    struct addrinfo *ai = nullptr;
    const int gai = getaddrinfo(host.c_str(), service, &hints, &ai);
    if (gai != 0) {
        *why = std::string("Cannot find ") + host + ": " + gai_strerror(gai);
        return -1;
    }

    int fd = -1;
    bool cancelled = false;
    *why = "Could not connect";
    for (struct addrinfo *a = ai; a != nullptr && fd < 0 && !cancelled; a = a->ai_next) {
        const int candidate = socket(a->ai_family, SOCK_STREAM | SOCK_NONBLOCK, 0);
        if (candidate < 0) {
            continue;
        }
        if (connect(candidate, a->ai_addr, a->ai_addrlen) == 0) {
            fd = candidate;
            break;
        }
        if (errno != EINPROGRESS) {
            *why = std::string("Could not connect: ") + strerror(errno);
            close(candidate);
            continue;
        }
        struct pollfd fds[2] = {{candidate, POLLOUT, 0}, {wake_[0], POLLIN, 0}};
        const auto deadline = std::chrono::steady_clock::now()
                + std::chrono::milliseconds(connectTimeoutMs_);
        int err = ETIMEDOUT;
        // The doorbell is in this poll so that a disconnect while the socket is
        // still opening does not have to wait out the deadline. But the app
        // rings it for every command it queues, and one queued during the
        // connect — a focus change, the options the session screen sets on the
        // way in — is not a cancellation: it has to be drained and waited past,
        // or the very first connection of a session reports a server that never
        // answered while the second one works.
        for (;;) {
            int remaining = -1;
            if (connectTimeoutMs_ > 0) {
                remaining = (int) std::chrono::duration_cast<std::chrono::milliseconds>(
                        deadline - std::chrono::steady_clock::now()).count();
                remaining = remaining < 0 ? 0 : remaining;
            }
            fds[0].revents = fds[1].revents = 0;
            const int r = poll(fds, 2, remaining);
            if (r < 0) {
                if (errno == EINTR) {
                    continue;
                }
                err = errno;
                break;
            }
            if (r == 0) {
                err = ETIMEDOUT;
                break;
            }
            if ((fds[1].revents & POLLIN) != 0) {
                char buf[64];
                while (read(wake_[0], buf, sizeof(buf)) > 0) {
                    // the doorbell, and nothing in it
                }
                const std::lock_guard<std::mutex> guard(lock_);
                if (quit_) {
                    cancelled = true;
                    break;
                }
            }
            if ((fds[0].revents & (POLLOUT | POLLERR | POLLHUP)) != 0) {
                socklen_t len = sizeof(err);
                if (getsockopt(candidate, SOL_SOCKET, SO_ERROR, &err, &len) != 0) {
                    err = errno;
                }
                break;
            }
        }
        if (!cancelled && err == 0) {
            fd = candidate;
            break;
        }
        // An empty reason is what the caller reads as "somebody asked for this".
        *why = cancelled ? ""
                : err == ETIMEDOUT ? "The server did not answer"
                : std::string("Could not connect: ") + strerror(err);
        close(candidate);
    }
    freeaddrinfo(ai);

    if (fd >= 0) {
        fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) & ~O_NONBLOCK);
        serverHost_ = host;
        serverPort_ = port;
    }
    return fd;
}

void Session::run() {
    JNIEnv *env = nullptr;
    vm_->AttachCurrentThread(&env, nullptr);

    std::string why;
    const int fd = openSocket(&why);
    if (fd < 0) {
        closed(why);
        vm_->DetachCurrentThread();
        return;
    }

    fd_.store(fd);
    std::unique_ptr<network::TcpSocket> sock;
    std::unique_ptr<Conn> conn;
    std::string detail;
    try {
        sock.reset(new network::TcpSocket(fd));
        installSecurityTypes();
        conn.reset(new Conn(this));
        conn->setShared(shared_);
        // Nothing is negotiated yet, so this is only the state the connection
        // starts in; the pixel format it decides is asked for in initDone.
        applyPicture(conn.get());
        conn->setServerName(serverHost_.c_str());
        conn->setStreams(&sock->inStream(), &sock->outStream());
        conn->initialiseProtocol();

        for (;;) {
            bool paused;
            std::deque<Cmd> pending;
            {
                std::unique_lock<std::mutex> guard(lock_);
                if (quit_) {
                    break;
                }
                paused = paused_;
                // Held rather than dropped until the connection is up: every
                // command below needs a writer, and there is none until the
                // handshake finishes — which can take as long as somebody
                // takes to answer a question about a certificate.
                if (connected_) {
                    pending.swap(queue_);
                }
            }
            for (Cmd &cmd : pending) {
                runCmd(conn.get(), cmd);
            }
            {
                const std::lock_guard<std::mutex> guard(lock_);
                if (quit_) {
                    break;
                }
            }

            sock->outStream().flush();
            setTraffic((jlong) conn->getInStream()->pos(),
                       (jlong) conn->getOutStream()->length());

            // Anything already in the buffer is a message nobody is going to
            // be told about by poll().
            bool buffered = !paused && sock->inStream().hasData(1);
            if (!buffered) {
                struct pollfd fds[2];
                int n = 0;
                fds[n++] = {wake_[0], POLLIN, 0};
                if (!paused) {
                    fds[n++] = {sock->getFd(), POLLIN, 0};
                }
                const int timeout = core::Timer::checkTimeouts();
                const int r = poll(fds, n, timeout > 0 ? timeout : -1);
                if (r < 0 && errno != EINTR) {
                    break;
                }
                if (r > 0 && (fds[0].revents & POLLIN) != 0) {
                    char buf[64];
                    while (read(wake_[0], buf, sizeof(buf)) > 0) {
                        // the doorbell, and nothing in it
                    }
                }
                if (n < 2 || (fds[1].revents & (POLLIN | POLLERR | POLLHUP)) == 0) {
                    continue;
                }
            }

            // processMsg() handles at most one message, so this loops until the
            // socket's buffer is empty or the queue needs draining.
            while (conn->processMsg()) {
                core::Timer::checkTimeouts();
                const std::lock_guard<std::mutex> guard(lock_);
                if (quit_ || !queue_.empty()) {
                    break;
                }
            }
        }
    } catch (rdr::end_of_stream &e) {
        detail = "The connection was lost";
    } catch (rfb::auth_cancelled &e) {
        detail = "";
    } catch (rfb::auth_error &e) {
        detail = std::string("Authentication failed: ") + e.what();
    } catch (std::exception &e) {
        detail = e.what();
    }

    bool asked;
    {
        const std::lock_guard<std::mutex> guard(lock_);
        asked = quit_;
    }
    if (conn) {
        try {
            conn->close();
        } catch (std::exception &) {
            // Already broken, and this is the goodbye.
        }
    }

    {
        // The reader may be inside readRegion; the framebuffer goes away with
        // the connection, so the copy it reads must stop existing first.
        const std::unique_lock<std::shared_mutex> guard(fbLock_);
        conn.reset();
        sock.reset();
        shadow_.clear();
        shadowW_ = shadowH_ = 0;
    }

    closed(asked && detail.empty() ? "" : (detail.empty() ? "The connection was lost" : detail));
    vm_->DetachCurrentThread();
}

// ---- pixels, from whichever thread is drawing ----------------------------

bool Session::readRegion(JNIEnv *env, int x, int y, int w, int h,
                         jobject bitmap, int dstX, int dstY) {
    AndroidBitmapInfo info;
    if (w <= 0 || h <= 0
            || AndroidBitmap_getInfo(env, bitmap, &info) != ANDROID_BITMAP_RESULT_SUCCESS
            || info.format != ANDROID_BITMAP_FORMAT_RGBA_8888
            || dstX < 0 || dstY < 0
            || (uint32_t) (dstX + w) > info.width || (uint32_t) (dstY + h) > info.height) {
        return false;
    }

    const std::shared_lock<std::shared_mutex> guard(fbLock_);
    if (shadow_.empty() || x < 0 || y < 0 || x + w > shadowW_ || y + h > shadowH_) {
        return false;
    }
    void *dst = nullptr;
    if (AndroidBitmap_lockPixels(env, bitmap, &dst) != ANDROID_BITMAP_RESULT_SUCCESS) {
        return false;
    }
    for (int row = 0; row < h; row++) {
        const uint32_t *src = shadow_.data() + (size_t) (y + row) * (size_t) shadowW_ + x;
        uint8_t *out = (uint8_t *) dst + (size_t) (dstY + row) * info.stride
                + (size_t) dstX * 4u;
        memcpy(out, src, (size_t) w * 4u);
    }
    AndroidBitmap_unlockPixels(env, bitmap);
    return true;
}

bool Session::readThumbnail(JNIEnv *env, int step, jobject bitmap) {
    AndroidBitmapInfo info;
    if (step < 1
            || AndroidBitmap_getInfo(env, bitmap, &info) != ANDROID_BITMAP_RESULT_SUCCESS
            || info.format != ANDROID_BITMAP_FORMAT_RGBA_8888) {
        return false;
    }

    const std::shared_lock<std::shared_mutex> guard(fbLock_);
    if (shadow_.empty()) {
        return false;
    }
    const int tw = (shadowW_ + step - 1) / step;
    const int th = (shadowH_ + step - 1) / step;
    if ((uint32_t) tw > info.width || (uint32_t) th > info.height) {
        return false;
    }
    void *dst = nullptr;
    if (AndroidBitmap_lockPixels(env, bitmap, &dst) != ANDROID_BITMAP_RESULT_SUCCESS) {
        return false;
    }
    for (int row = 0; row < th; row++) {
        const uint32_t *src = shadow_.data() + (size_t) (row * step) * (size_t) shadowW_;
        uint32_t *out = (uint32_t *) ((uint8_t *) dst + (size_t) row * info.stride);
        for (int col = 0; col < tw; col++) {
            out[col] = src[col * step];
        }
    }
    AndroidBitmap_unlockPixels(env, bitmap);
    return true;
}

jobjectArray Session::info(JNIEnv *env) {
    std::string desktop, protocol, security, serverPF, viewerPF;
    {
        const std::lock_guard<std::mutex> guard(infoLock_);
        desktop = infoDesktop_;
        protocol = infoProtocol_;
        security = infoSecurity_;
        serverPF = infoServerPF_;
        viewerPF = infoViewerPF_;
    }
    const int encoding = infoEncoding_;
    char speed[32];
    snprintf(speed, sizeof(speed), "%u kbit/s", infoLineSpeed_.load() / 1000);

    const char *values[] = {
            desktop.c_str(),
            protocol.c_str(),
            "TCP",
            security.c_str(),
            encoding < 0 ? "" : rfb::encodingName(encoding),
            speed,
            serverPF.c_str(),
            viewerPF.c_str(),
    };
    const int n = (int) (sizeof(values) / sizeof(values[0]));
    jobjectArray out = env->NewObjectArray(n, env->FindClass("java/lang/String"), nullptr);
    if (out == nullptr) {
        return nullptr;
    }
    for (int i = 0; i < n; i++) {
        // The desktop name is the server's, and their reader guarantees only
        // that it is valid UTF-8 — which a four-byte sequence makes exactly not
        // the modified UTF-8 NewStringUTF wants. The rest of these the library
        // printed.
        jstring js = i == 0 ? fromUtf8(env, values[i]) : env->NewStringUTF(values[i]);
        env->SetObjectArrayElement(out, i, js);
        env->DeleteLocalRef(js);
    }
    return out;
}

Session *handleOf(jlong handle) {
    return (Session *) (intptr_t) handle;
}

} // namespace

// ---- the JNI surface -----------------------------------------------------

#define NATIVE(ret, name) extern "C" JNIEXPORT ret JNICALL \
    Java_net_pgaskin_remotedesktop_backend_tigervnc_TigerVncNative_##name

NATIVE(jstring, nativeVersion)(JNIEnv *env, jclass) {
    return env->NewStringUTF("TigerVNC " PACKAGE_VERSION);
}

NATIVE(jlong, nativeCreate)(JNIEnv *env, jclass, jobject listener, jstring address,
                            jstring userName, jstring password, jboolean shared,
                            jboolean anonymousTls, jint encoding, jint compressLevel,
                            jint qualityLevel, jint colorLevel, jboolean h264,
                            jint connectTimeoutMs) {
    initLogging();
    if (gCallbacksClass == nullptr) {
        jclass k = env->GetObjectClass(listener);
        mConnected = env->GetMethodID(k, "onConnected", "(II)V");
        mDesktopSize = env->GetMethodID(k, "onDesktopSize", "(II)V");
        mDamage = env->GetMethodID(k, "onDamage", "(IIII)V");
        mFrameEnd = env->GetMethodID(k, "onFrameEnd", "()V");
        mCursor = env->GetMethodID(k, "onCursor", "([IIIIIJ)V");
        mBell = env->GetMethodID(k, "onBell", "()V");
        mClipboard = env->GetMethodID(k, "onClipboard", "(Ljava/lang/String;)V");
        mCredentialsNeeded = env->GetMethodID(k, "onCredentialsNeeded", "(Z)V");
        mQuestion = env->GetMethodID(k, "onQuestion", "(Ljava/lang/String;Ljava/lang/String;)V");
        mUnverified = env->GetMethodID(k, "onUnverified", "(Ljava/lang/String;)V");
        mClosed = env->GetMethodID(k, "onClosed", "(Ljava/lang/String;)V");
        // Last, and that is the point: it is what every other caller tests, so
        // publishing it first would let a second one past while the method ids
        // above were still zero.
        gCallbacksClass = (jclass) env->NewGlobalRef(k);
    }

    Session *s = new Session(env, listener, toString(env, address), toString(env, userName),
                             toString(env, password), shared != JNI_FALSE,
                             anonymousTls != JNI_FALSE, encoding, compressLevel,
                             qualityLevel, colorLevel, h264 != JNI_FALSE, connectTimeoutMs);
    if (!s->start()) {
        s->destroy();
        delete s;
        return 0;
    }
    return (jlong) (intptr_t) s;
}

NATIVE(void, nativeAnswerCredentials)(JNIEnv *env, jclass, jlong handle, jstring userName,
                                      jstring password) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        const std::string user = toString(env, userName);
        if (password == nullptr) {
            s->answerCredentials(user, nullptr);
        } else {
            const std::string secret = toString(env, password);
            s->answerCredentials(user, secret.c_str());
        }
    }
}

// TigerVNC finds its known-hosts file through the environment, whose HOME on
// Android is not a directory an app may write to. Both are set rather than one
// because the XDG variable is only consulted after a home directory is found —
// and what it names is the *parent*: the library's own directory under it is
// made here, since nothing in the library makes it and a store that fails is
// only a line in the log.
NATIVE(void, nativeSetStateDir)(JNIEnv *env, jclass, jstring path) {
    const std::string dir = toString(env, path);
    if (!dir.empty()) {
        setenv("XDG_STATE_HOME", dir.c_str(), 1);
        setenv("HOME", dir.c_str(), 0);
        mkdir((dir + "/tigervnc").c_str(), 0700);
    }
}

NATIVE(void, nativeAnswerQuestion)(JNIEnv *, jclass, jlong handle, jboolean yes) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->answerQuestion(yes != JNI_FALSE);
    }
}

NATIVE(void, nativeDisconnect)(JNIEnv *, jclass, jlong handle) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->disconnect();
    }
}

NATIVE(void, nativeDestroy)(JNIEnv *, jclass, jlong handle) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->destroy();
        delete s;
    }
}

NATIVE(void, nativePointer)(JNIEnv *, jclass, jlong handle, jint x, jint y, jint buttonMask) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->post({CMD_POINTER, x, y, buttonMask});
    }
}

NATIVE(void, nativeKeyDown)(JNIEnv *, jclass, jlong handle, jint keysym, jint keyId) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->post({CMD_KEY_DOWN, keysym, keyId});
    }
}

NATIVE(void, nativeKeyUp)(JNIEnv *, jclass, jlong handle, jint keyId) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->post({CMD_KEY_UP, keyId});
    }
}

NATIVE(void, nativeReleaseAllKeys)(JNIEnv *, jclass, jlong handle) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->post({CMD_RELEASE_KEYS});
    }
}

NATIVE(void, nativeFocus)(JNIEnv *, jclass, jlong handle, jboolean focused) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->setFocus(focused != JNI_FALSE);
    }
}

NATIVE(void, nativeViewOnly)(JNIEnv *, jclass, jlong handle, jboolean viewOnly) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->setViewOnly(viewOnly != JNI_FALSE);
    }
}

NATIVE(jboolean, nativeCanResize)(JNIEnv *, jclass, jlong handle) {
    Session *s = handleOf(handle);
    return s != nullptr && s->canResize() ? JNI_TRUE : JNI_FALSE;
}

NATIVE(jintArray, nativeMonitors)(JNIEnv *env, jclass, jlong handle) {
    Session *s = handleOf(handle);
    const std::vector<jint> screens = s != nullptr ? s->screens() : std::vector<jint>();
    jintArray out = env->NewIntArray(static_cast<jsize>(screens.size()));
    if (out != nullptr && !screens.empty()) {
        env->SetIntArrayRegion(out, 0, static_cast<jsize>(screens.size()), screens.data());
    }
    return out;
}

NATIVE(void, nativeRequestDesktopSize)(JNIEnv *, jclass, jlong handle, jint width, jint height) {
    Session *s = handleOf(handle);
    if (s != nullptr && width > 0 && height > 0 && width <= 65535 && height <= 65535) {
        s->post({CMD_RESIZE, width, height});
    }
}

NATIVE(void, nativeClipboard)(JNIEnv *env, jclass, jlong handle, jstring text) {
    Session *s = handleOf(handle);
    if (s != nullptr && text != nullptr) {
        Cmd cmd{CMD_CLIPBOARD};
        cmd.text = toUtf8(env, text);
        s->post(std::move(cmd));
    }
}

NATIVE(void, nativeSetPicture)(JNIEnv *, jclass, jlong handle, jint encoding,
                               jint compressLevel, jint qualityLevel, jint colorLevel,
                               jboolean h264) {
    Session *s = handleOf(handle);
    if (s != nullptr) {
        s->setPicture(encoding, compressLevel, qualityLevel, colorLevel, h264 != JNI_FALSE);
        s->post({CMD_PICTURE});
    }
}

NATIVE(jobjectArray, nativeInfo)(JNIEnv *env, jclass, jlong handle) {
    Session *s = handleOf(handle);
    return s == nullptr ? nullptr : s->info(env);
}

NATIVE(jlongArray, nativeTraffic)(JNIEnv *env, jclass, jlong handle) {
    Session *s = handleOf(handle);
    if (s == nullptr) {
        return nullptr;
    }
    jlong both[2];
    s->traffic(both);
    jlongArray out = env->NewLongArray(2);
    if (out != nullptr) {
        env->SetLongArrayRegion(out, 0, 2, both);
    }
    return out;
}

NATIVE(jboolean, nativeReadRegion)(JNIEnv *env, jclass, jlong handle, jint x, jint y,
                                   jint w, jint h, jobject bitmap, jint dstX, jint dstY) {
    Session *s = handleOf(handle);
    return s != nullptr && s->readRegion(env, x, y, w, h, bitmap, dstX, dstY)
            ? JNI_TRUE : JNI_FALSE;
}

NATIVE(jboolean, nativeReadThumbnail)(JNIEnv *env, jclass, jlong handle, jint step,
                                      jobject bitmap) {
    Session *s = handleOf(handle);
    return s != nullptr && s->readThumbnail(env, step, bitmap) ? JNI_TRUE : JNI_FALSE;
}
