// SPDX-FileCopyrightText: 2026 Patrick Gaskin
// SPDX-License-Identifier: GPL-3.0-or-later

plugins {
    id 'groovy'
}

//sourceSets.main.groovy.srcDir '../app/buildSrc/src/main/groovy'
//sourceSets.main.groovy.srcDir '../backends/buildSrc/src/main/groovy'
sourceSets.main.groovy.srcDir '../realvnc/buildSrc/src/main/groovy'
